<?php

namespace Modules\Product\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = array(
            array(
                "name" => "Wild Delivery Blue",
                "description" => "TEES WILD DELIVERY \r\nPrice : Idr 135.000\r\nSize : S - M & XL, TEES WILD DELIVERY, TEES WILD DELIVERY",
                "image" => "images/products/wsAJHL4lXGPuYXAcwOn5XUrHSW568kz2kePqxTWF.jpeg",
                "price" => 135000,
                "weight" => 100,
                "category_id" => 5,
                "size_id" => 1,
                "status" => 1,
            ),
            array(
                "name" => "Van Red",
                "description" => "TEES VAN RED",
                "image" => "images/products/9FCDRKl2RntNGxsxIV8DtJDUGzSBmJuoWGNKYIT5.jpeg",
                "price" => 135000,
                "weight" => 100,
                "category_id" => 5,
                "size_id" => 1,
                "status" => 1,
            ),
            array(
                "name" => "Tees Log Box 11",
                "description" => "Tees Log Box made with lightweight, 4.5oz Ringspun cotton which makes this tee extra soft.\r\nTees Log Box made with lightweight, 4.5oz Ringspun cotton which makes this tee extra soft.",
                "image" => "images/products/xMc8TnPq3lO9F3afiP7xgLQCgP6g7d3WNVqlqMlX.jpeg",
                "price" => 135000,
                "weight" => 100,
                "category_id" => 5,
                "size_id" => 1,
                "status" => 1,
            ),
            array(
                "name" => "Tees Grunge",
                "description" => "Hanes 100% Combed Ringspun Cotton Nano T-Shirt. Made with lightweight, 4.5oz Ringspun cotton which makes this tee extra soft.",
                "image" => "images/products/QgMbo8y0SmDog0VKqlMExTPqVMDHCsA2RvRfLPmI.jpeg",
                "price" => 135000,
                "weight" => 100,
                "category_id" => 5,
                "size_id" => 1,
                "status" => 1,
            ),
            array(
                "name" => "Pattern Shirt Yellow",
                "description" => "PATTERN SHIRT \r\nCode : HS 2459 \r\nPrice : Idr 195.000\r\nSize : S - M - L - XL",
                "image" => "images/products/5zTMAjPhtq4lXvgT9DdjMTawphabzmbIZrEPuJ8Q.jpeg",
                "price" => 195000,
                "weight" => 200,
                "category_id" => 6,
                "size_id" => 1,
                "status" => 1,
            ),
            array(
                "name" => "Denim Long Pants Navy",
                "description" => "Denim Long Pants Navy",
                "image" => "images/products/N9rGl7NyALTsE1djya4DYXjAQNpp8pTSisPj0UUZ.jpeg",
                "price" => 250000,
                "weight" => 1000,
                "category_id" => 7,
                "size_id" => 2,
                "status" => 1,
            ),
            array(
                "name" => "Navy Cargo Pants",
                "description" => "NAVY CARGO PANTS",
                "image" => "images/products/tzqj4TRtkPY0O4ZgE7fy6m7OaFidEnpJqKVmkMwi.jpeg",
                "price" => 300000,
                "weight" => 1000,
                "category_id" => 7,
                "size_id" => 2,
                "status" => 1,
            ),
            array(
                "name" => "Khakis Chino Pants",
                "description" => "KHAKIS CHINO PANTS",
                "image" => "images/products/NMjKP4fHpR5VE0tpSCj7ETHe5JSAElJIuqrhBAKJ.jpeg",
                "price" => 310000,
                "weight" => 1000,
                "category_id" => 7,
                "size_id" => 2,
                "status" => 1,
            ),
            array(
                "name" => "Jogger Jeans",
                "description" => "JOGGER JEANS \r\nCode : SJJ 05\r\nSize : 30 - 32 - 34\r\nOrder SMS / WA 0896 7219 8887 Line",
                "image" => "images/products/9MbAwsDFuXf1Af3H7tOj15DVPTgUpdUg4EQnnuZV.jpeg",
                "price" => 250000,
                "weight" => 1000,
                "category_id" => 7,
                "size_id" => 2,
                "status" => 0,
            ),
            array(
                "name" => "Pants A",
                "description" => "test test tes",
                "image" => "images/products/K7BWZAPbwxGGD36W0ldJvBb1OMYpK8t7AwBQmgbk.jpeg",
                "price" => 100000,
                "weight" => 1000,
                "category_id" => 7,
                "size_id" => 2,
                "status" => 0,
            ),
            array(
                "name" => "Sweater Wild Grey",
                "description" => "Ini dia bahan favorit anak-anak muda di daerah perkotaan. Bahan ini biasa diandalkan clothing line dan distro karena tipis dan tidak panas. Bahan Combed 30s menggunakan gramasi yang berkisar antara 140 – 160 gr/m2 dengan untuk jenis rajutan Single Knitt.",
                "image" => "images/products/rCy7eWtBDU6lKjz7PXihHkUXxr4PrdfASEXOA3XE.jpeg",
                "price" => 270000,
                "weight" => 250,
                "category_id" => 8,
                "size_id" => 1,
                "status" => 1,
            ),
            array(
                "name" => "Sweater Chillin",
                "description" => "Ini dia bahan favorit anak-anak muda di daerah perkotaan. Bahan ini biasa diandalkan clothing line dan distro karena tipis dan tidak panas. Bahan Combed 30s menggunakan gramasi yang berkisar antara 140 – 160 gr/m2 dengan untuk jenis rajutan Single Knitt.",
                "image" => "images/products/wUmmOeHjK0pWygFfSY4QilBm8alJpjgcGrgnrRjX.jpeg",
                "price" => 270000,
                "weight" => 250,
                "category_id" => 8,
                "size_id" => 1,
                "status" => 1,
            ),
            array(
                "name" => "Harrington Jacket",
                "description" => "Harrington Jacket Green",
                "image" => "images/products/IZwtUje5zhMwq1Px9N9k6Bq3DRsw2EmkrERfXh5e.jpeg",
                "price" => 325000,
                "weight" => 1000,
                "category_id" => 9,
                "size_id" => 1,
                "status" => 1,
            ),
            array(
                "name" => "Zip Hoodie",
                "description" => "Zip Hoodie Smile Green",
                "image" => "images/products/kQ4pJs1e6pJKWsrEkf3CCCr9Tcg7pbweeFdlB7ml.jpeg",
                "price" => 295000,
                "weight" => 1000,
                "category_id" => 9,
                "size_id" => 1,
                "status" => 1,
            ),
            array(
                "name" => "Varsity Jacket",
                "description" => "Varsity Jacket Black",
                "image" => "images/products/A8y5JQqNVLapHk8L2RRWS1oqlSB0Ya8OLIfZQSq9.jpeg",
                "price" => 350000,
                "weight" => 1000,
                "category_id" => 9,
                "size_id" => 1,
                "status" => 1,
            ),
            array(
                "name" => "Denim Jacket",
                "description" => "Denim Jacket",
                "image" => "images/products/P3CE5GKWNRedYDObQXlIzXjYOvAMix0Kgb9YTVKe.jpeg",
                "price" => 410000,
                "weight" => 1000,
                "category_id" => 9,
                "size_id" => 1,
                "status" => 1,
            ),
            array(
                "name" => "Coach Jacket Red",
                "description" => "COACH JACKET RED",
                "image" => "images/products/9VTU6qM2CBCmkbFlrM1PHwjQreMqbXoEFmzljrHx.jpeg",
                "price" => 325000,
                "weight" => 100,
                "category_id" => 9,
                "size_id" => 1,
                "status" => 1,
            ),
            array(
                "name" => "Polo Caps White",
                "description" => "Polo Caps White",
                "image" => "images/products/QhEuTSLYjPpzy5MLNjryPMv2lWArvGhxQcKvBDKl.jpeg",
                "price" => 140000,
                "weight" => 500,
                "category_id" => 10,
                "size_id" => 3,
                "status" => 1,
            ),
            array(
                "name" => "Polo Caps Wild Yellow",
                "description" => "Polo Caps Wild Yellow",
                "image" => "images/products/NqUe054vlS08BbyXHX5EWsTGy0emmY7eSvJMBnpt.jpeg",
                "price" => 140000,
                "weight" => 500,
                "category_id" => 10,
                "size_id" => 3,
                "status" => 1,
            ),
            array(
                "name" => "Snapback",
                "description" => "Snapback Wild Youth Black",
                "image" => "images/products/GRYX3xE9EhcX7orXOS9ClIJEcVi6CgybL3uND4gD.jpeg",
                "price" => 150000,
                "weight" => 500,
                "category_id" => 10,
                "size_id" => 3,
                "status" => 1,
            ),
            array(
                "name" => "Trucker",
                "description" => "Trucker Hat Starcross Wild Youth",
                "image" => "images/products/nmls1x51lbwMjSZvCSjlJr11r1oeaHxwZLDkHt2z.jpeg",
                "price" => 135000,
                "weight" => 500,
                "category_id" => 10,
                "size_id" => 3,
                "status" => 1,
            ),
            array(
                "name" => "5 Panel Hat",
                "description" => "Tropical 5 panel Hat",
                "image" => "images/products/vzfuD3bbNW12EIIMoNRDeBT29CbKcxBVaYnTUwmM.jpeg",
                "price" => 135000,
                "weight" => 500,
                "category_id" => 10,
                "size_id" => 3,
                "status" => 1,
            ),
            array(
                "name" => "Bucket Hat",
                "description" => "Bucket Hat Brown",
                "image" => "images/products/QSH72zbaWpUmbjgKFLl9DxNAO7US8t4NPBPuBvSn.jpeg",
                "price" => 120000,
                "weight" => 500,
                "category_id" => 10,
                "size_id" => 3,
                "status" => 1,
            ),
            array(
                "name" => "Wallet Black",
                "description" => "WALLET \r\nCode : WMS 293",
                "image" => "images/products/sOkgPLEZarJcXh6dSHKwFhC1lqqE333cmJk23F3R.jpeg",
                "price" => 115000,
                "weight" => 100,
                "category_id" => 11,
                "size_id" => 3,
                "status" => 1,
            ),
            array(
                "name" => "Sandals Brown",
                "description" => "SANDALS\r\nSize : S (38-39) - M (40-41) - L (42-43) - XL (44)",
                "image" => "images/products/u358hVGmUiLqLqkBPlwAeJxPTK85hBi8tX5BqLmq.jpeg",
                "price" => 120000,
                "weight" => 500,
                "category_id" => 12,
                "size_id" => 1,
                "status" => 0,
            ),
            array(
                "name" => "Sandals Maroon",
                "description" => "SANDALS\r\nSize : S (38-39) - M (40-41) - L (42-43) - XL (44)",
                "image" => "images/products/urOjp4Tnb0ZQc4z7t56BuOB9sYLv4OB3X9mvoFbq.jpeg",
                "price" => 120000,
                "weight" => 500,
                "category_id" => 12,
                "size_id" => 1,
                "status" => 1,
            ),
            array(
                "name" => "Backpack Green",
                "description" => "BACKPACK GREEN",
                "image" => "images/products/3A96N3NpCm43hnNo4SJXCZv2fge4XvVezVoP7wkc.jpeg",
                "price" => 240000,
                "weight" => 1000,
                "category_id" => 13,
                "size_id" => 3,
                "status" => 1,
            ),
            array(
                "name" => "Backpack + Pouch Black",
                "description" => "BACKPACK + POUCH",
                "image" => "images/products/ChM4PwWQTB3h3ffMsJxj97cLHKko5LFln9BaoFA9.jpeg",
                "price" => 240000,
                "weight" => 1000,
                "category_id" => 13,
                "size_id" => 3,
                "status" => 1,
            ),
            array(
                "name" => "Backpack + Pouch Grey",
                "description" => "BACKPACK + POUCH",
                "image" => "images/products/F9NHAnPOcEOqKns7faK9eKq3om2Iar7nc3fZsLi5.jpeg",
                "price" => 240000,
                "weight" => 1000,
                "category_id" => 13,
                "size_id" => 3,
                "status" => 1,
            ),
            array(
                "name" => "Backpack Grey",
                "description" => "Backpack Grey",
                "image" => "images/products/pLzJ7vKuSzYlbk8BzEYYNCVGl6MgGxD7dpRvHp3V.jpeg",
                "price" => 240000,
                "weight" => 1000,
                "category_id" => 13,
                "size_id" => 3,
                "status" => 1,
            ),
            array(
                "name" => "Waistbag Black",
                "description" => "Waistbag Black Starcross\r\nMaterial : Canvas",
                "image" => "images/products/Xkl8y8PtGzfOBJsgr27RkxkjRi0Jmv410enrVg5V.jpeg",
                "price" => 220000,
                "weight" => 500,
                "category_id" => 13,
                "size_id" => 3,
                "status" => 0,
            ),
            array(
                "name" => "Waistbag Grey",
                "description" => "Material : Canvas\r\nDimensi (PxLxT) : 30x10x13",
                "image" => "images/products/PnlTSlvFBtxaW8MyfmqWu2eQ1tH56wPf04NGGCiJ.jpeg",
                "price" => 220000,
                "weight" => 150,
                "category_id" => 13,
                "size_id" => 3,
                "status" => 1,
            ),
            array(
                "name" => "Camo Basic Tees",
                "description" => "Camo Basic Tees",
                "image" => "images/products/IhxHDBwAynMvyxBQA0XzwUymbhOrsNmmnS76cTki.jpeg",
                "price" => 225000,
                "weight" => 500,
                "category_id" => 16,
                "size_id" => 1,
                "status" => 1,
            ),
            array(
                "name" => "Wild Youth Flame",
                "description" => "iPhone Hardcase 5 / 5s",
                "image" => "images/products/tkImMFeeib0nJmPvKcF4GDKGU9i8YHWXlINKYIA3.jpeg",
                "price" => 75000,
                "weight" => 500,
                "category_id" => 22,
                "size_id" => 3,
                "status" => 1,
            ),
            array(
                "name" => "Starcross Red",
                "description" => "iPhone Hardcase 5 / 5s",
                "image" => "images/products/NQaMmntDzyYituNnU2mjLO4qE9egmxefr1NF6FJr.jpeg",
                "price" => 75000,
                "weight" => 500,
                "category_id" => 22,
                "size_id" => 3,
                "status" => 1,
            ),
            array(
                "name" => "Eyewear Camo",
                "description" => "STARCROSS EYEWEAR \r\nCode : EWS 07 \r\nPrice : Idr 75.000",
                "image" => "images/products/oq1vZiMFQ9qXL3Uw7lTCBCK8Xvy2rV92EqevqTCJ.jpeg",
                "price" => 75000,
                "weight" => 500,
                "category_id" => 23,
                "size_id" => 3,
                "status" => 0,
            ),
            array(
                "name" => "Earphones Blue",
                "description" => "EARPHONES BLUE",
                "image" => "images/products/fRJ79l4ecpG2Od3LPEGZrIO8lM7TwCL0igRj4Rra.jpeg",
                "price" => 70000,
                "weight" => 500,
                "category_id" => 24,
                "size_id" => 3,
                "status" => 1,
            ),
            array(
                "name" => "Camouflage Zip Hoodie",
                "description" => "This well-crafted Camouflage Zip Hoodie produce in Limited Quantity",
                "image" => "images/products/3ccxuLmcA8Oxrpvn6bwzgH7wutIh8EHfrAY0kjBJ.jpeg",
                "price" => 330000,
                "weight" => 1000,
                "category_id" => 15,
                "size_id" => 1,
                "status" => 1,
            ),
            array(
                "name" => "Hoodie Blue",
                "description" => "HOODIES",
                "image" => "images/products/URIzSOTXtAmAPZlfUEGZB8PtawjxQZ4lfxbphs2g.jpeg",
                "price" => 295000,
                "weight" => 1000,
                "category_id" => 15,
                "size_id" => 1,
                "status" => 1,
            ),
            array(
                "name" => "Hoodie Pattern Grey",
                "description" => "HOODIES PATTERN GREY",
                "image" => "images/products/HlKTgT426GVTDeadZR9aNTcGsUfanIAemj8hfi9F.jpeg",
                "price" => 325000,
                "weight" => 1000,
                "category_id" => 15,
                "size_id" => 1,
                "status" => 1,
            ),
        );
        
        foreach($products as $product) {
            App\Product::create($product);
        }

    }
}
