<?php

return [
    'prefix' => 'shipment',
    'origin' => 6989,
    'originType' => 'sub    district',
    'services' => ['pos', 'jne', 'tiki'],
    'blacklist' => ['Paketpos Valuable Goods', 'Paketpos Dangerous Goods', 'SDS', 'HDS', 'CRG'],
    'address' => "Jln. Cepakasari no 691 Jogokaryan Mantrijeron\r\nKOTA YOGYAKARTA - MANTRIJERON\r\nDI YOGYAKARTA 55143\r\nNomor Telpon : 089672198887",
    'zip_code' => 55222,
    'end_point_api' => env('RAJAONGKIR_ENDPOINTAPI', 'https://pro.rajaongkir.com/api/'),
    'api_key' => env('RAJAONGKIR_APIKEY', 'd985e449666dc41df8683c05e10d3289'),
    'couriers' => [
        'jne'       => 'Jalur Nugraha Ekakurir (JNE)',
        'pos'       => 'POS Indonesia (POS)',
        'tiki'      => 'Citra Van Titipan Kilat (TIKI)',
        'pcp'       => 'Priority Cargo and Package (PCP)',
        'esl'       => 'Eka Sari Lorena (ESL)',
        'rpx'       => 'RPX Holding (RPX)',
        'pandu'     => 'Pandu Logistics (PANDU)',
        'wahana'    => 'Wahana Prestasi Logistik (WAHANA)',
        'sicepat'   => 'SiCepat Express (SICEPAT)',
        'j&t'       => 'J&T Express (J&T)',
        'pahala'    => 'Pahala Kencana Express (PAHALA)',
        'cahaya'    => 'Cahaya Logistik (CAHAYA)',
        'sap'       => 'SAP Express (SAP)',
        'jet'       => 'JET Express (JET)',
        'indah'     => 'Indah Logistic (INDAH)',
        'slis'      => 'Solusi Express (SLIS)',
        'expedito*' => 'Expedito*',
        'dse'       => '21 Express (DSE)',
        'first'     => 'First Logistics (FIRST)',
        'ncs'       => 'Nusantara Card Semesta (NCS)',
        'star'      => 'Star Cargo (STAR)',
    ],
    'adapter' => [
        'rajaOngkir' => [
            'waybills' => [
                'starter' => [],
                'basic'   => [
                    'jne',
                ],
                'pro'     => [
                    'jne',
                    'pos',
                    'tiki',
                    'pcp',
                    'rpx',
                    'wahana',
                    'sicepat',
                    'j&t',
                    'sap',
                    'jet',
                    'dse',
                    'first',
                ],
            ],
            'supported' => [
                'starter' => [
                    'jne',
                    'pos',
                    'tiki',
                ],
                'basic'   => [
                    'jne',
                    'pos',
                    'tiki',
                    'pcp',
                    'esl',
                    'rpx',
                ],
                'pro'     => [
                    'jne',
                    'pos',
                    'tiki',
                    'rpx',
                    'esl',
                    'pcp',
                    'pandu',
                    'wahana',
                    'sicepat',
                    'j&t',
                    'pahala',
                    'cahaya',
                    'sap',
                    'jet',
                    'indah',
                    'slis',
                    'expedito*',
                    'dse',
                    'first',
                    'ncs',
                    'star',
                    'lion',
                    'ninja-express',
                    'idl',
                    'rex',
                ],
            ]
        ],
    ]
];
